project:
  type: book
  output-dir: _book

book:
  title: "Reproducible documentation for the study on geospatial relationship between plasma Se concetration in WRA & maize grain Se concentration in Malawi"
  subtitle: ""
  author: 
    - "Lucia Segovia De La Revilla"
    - "Claire Dooley"
    - "Edward Joy"
  date: "22/01/2024"
  repo-url: https://github.com/LuciaSegovia/geospatial_analysis/
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - data-description.qmd
    - data-processing.qmd
   # - modelling.qmd
    - references.qmd

  sidebar:
    tools:
      - icon: cloud-arrow-down
      #  href: https://dzvoti.github.io/r4hces/r4hces-data.zip
       # aria-label: Download data

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    number-offset: 1
    number-depth: 4
    toc-title: "On this page"
    code-fold: show 
    embed-resources: true
  pdf:
    documentclass: scrreprt
   
editor: source

# Do not evaluate code chunks
# eval: false
# callout-icon: false



