# Maize aggregation




### Maize Se estimates

Predicted-mean Se concentration in maize at different level of aggregation were calculated using a Linear Mixed Model using pH & MAT as covariates and the aggregation unit as the random effect. The covariates were selected following Gashu et al, (2019) method. The covariates that were selected (significant) for the maize Se map (kriging map) were mean atmospheric temperature (MAT) and pH. See: `Explora_Malawi_model.R`.

#### Maize modelling issues (check notes:`Maize-model_notes.md`)
 



### . Other crops 

There were some discussions around including or not other crops into the model. The rationale for inclusion is: 

1) the model will be more generalisable/ flexible: Because other countries may not have a unique dominant staple crop, as it is maize in Malawi. 
2) the model will account for spatial variation due to other crops, hence probably yielding more accurate results. 

However, the addition of more crops will add more complexity to the model due to:
 
 1) different crops may have a different food system. I.e, the catchment area (or foodshed), may be different. For instance, importing that crop or getting it from further away. 
 2) other crops are not equally important across the country, and all of them are less consumed than maize in all districts (see image)
 3) there are other uncertainties that may play a role, for instance, sesonality and the displacement of the household location, that may be more difficult to characterise with a more complex model.

 In addition, with this analysis were are using maize Se as a proxy for a) the spatial variation of Se in crops-livestock-human, b) the foodshed and/or food catchment area, and c) maize is the main crop consumed across the country in similar proportions (see images), while other grains are consumed in particular region and various amounts [@ref own analysis using IHS4]. We are not aiming to find a model that will be used to predict the plasma se of populations, as there are other potential sources of plasma Se variability that are not taken into consideration in this modelling excersise, such as fish intake, total food intake, etc. 

