---
title: "Reproducible data documentation for the study on geospatial relationship between plasma Se concetration in WRA & maize grain Se concentration in Malawi"
format: html
editor: source
---

# Intro

The objectives of these exploratory analysis are:

1)  to calculate the mean/median wealth and education level for each EA in Malawi, and to see if there are differences

2)  to start evaluating how to calculate the mean/median maize Se concentration at different level of spatial aggregation (i.e., from 5km radius up to regional averages).

## Dataset & Variables

### 1. Geo-referenced crop (maize) composition (Se in maize) in Malawi

a. Malawi maize grain and soil Se concentration dataset (2018). It is publicly available [here](https://github.com/rmlark/GeoNutrition/tree/main/Soil_Crop_comparisons/Malawi)

File name: GeoNutrition/Soil_Crop_comparisons/Malawi/Malawi_grain_soil.xlsx 
 data/maize/Malawi_Grain.csv

**Variables**:

-   Latitude/ Longitude
-   Crop
-   Se_triplequad
-   Zn
-   pH_Wa (pH in water)
-   N_pct
-   Org_pct
-   BIO1
-   BIO12
-   TIM

b. Malawi maize grain and soil Se concentration dataset (2009-2010). It is publicly available [here](). 

File name: data/maize/2009_mwi-maize.xls


**Variables**:

c. Malawi crops, including maize, mineral concentration dataset (2012-2013). It is publicly available [here](). 

File name: data/maize/2009_mwi-maize.xl

**Variables**:


### 2. Geo-referenced biomarkers data (Plasma Se in WRA) in Malawi 

Malawi DHS - MNS 2015-2016. Access need to be requested to DHS data [here](https://dhsprogram.com/methodology/survey/survey-display-483.cfm).

**File of interest & variables**:

a. Micronutrient survey data (MW_WRA). This dataset provided information on biomarker data and other biological data for women of reproductive age in Malawi. 

#TODO: Find the variable for CRP levels

-   mregion (region) [1-3 = N->S]
-   mtype (urban/rural) [U-R = 1-2] 
-   m04  (gender)
-   mcluster (cluster number - PSU?)
-   mnumber (husehold number)
-   mweight (Micro nutrient survey household weight (6 decimals))
-   m01 (line number - individual ID within HH)
-   m07 (age)
-   m435 (weight)
-   m436 (height)
-   sel (Plasma Se (ng/ml))
-   m415 (Took any kind of vitamin or mineral tablet/syrup/powder)

b. Questionnaire data (MWIR7). This dataset provided inforamtion on socioeconomic factors. We downloaded both the .dat and .dta file because the file with .dat extansion was not opening in R. It was not corrupted as we could open the .MAP with Notepad+, and we could see all recode doucmentation. 

These variables provide information at individual level.

Variables of interest:

-   v101/V024 (De facto region of residence)
-   sdist - (district). 
-   v022 (survey strata). Note that v022 & v023 are strata Urban/rural district. This shouldn't be used for MNS because the representativeness (and strata in MNS are region+rural/urban.
-   v005 (Woman's sample weights, divide it by 1000000 before applying the weighting factor). Not to be used for MNS, as MNS is a subset and has its own survey weights. 

-   v106 (Highest educational level)

-   v155 (Literacy)

-   v190 (Wealth index)

-   v002 (Household number)

-   v001 (Cluster number)

b.  MWGE7AFL (geographic data)  Variable: DHSCLUST (to be used w/ V001). 

GPS displacement within district. 

#TODO: Check README and recommended readings to understand displacement and what it is possible and not possible for analysis. 

### 3. Boundaries of Malawi

Malawi administrative boundaries, from the higher to the smallest area: Region> District> Traditional Authorities (TA)> Enumeration Areas (EA). 

- GADM maps and data, (gadm40_MWI_shp), https://gadm.org/download_country.html, The file for the EAs has some issues that lead some points in the lake. Hence, we found a different file with the Malawi boudaries, 

- Malawi NSO from HDX (Humanitarian datasets), (mwi_adm_nso_hotosm_20230329), https://data.humdata.org/dataset/cod-ab-mwi

- Population over Enumeration Areas NSO, (eas_bnd) https://www.masdap.mw/catalogue/#/dataset/126, This layer shows the distribution of the population over the country of Malawi on the basis of enumeration area boundary. Data producer is the National Statistical Office.

- Echo2 priritization, These files covered up to EAs. (depricated - Updated version: Population over Enumeration Areas NSO)

- GeoBoundaries: It also has 3 level of boudaries: 1-region, 2-district, 3-TA. These files has no EA boundaries (depricated).

Other boundaries in Malawi, including agro-ecological zones, agricultural land, body water, national parks, etc. 

We are not incluiding the AEZs boundaries because they are only 4 AEZs in Malawi, hence areas are too big to get any meanful spatial variation, and/or level of aggregation. Note: The AEZ can be found in the Scoping review (R project, data folder), and further inforamtion can be found in [here](https://climateknowledgeportal.worldbank.org/sites/default/files/2019-06/CSA%20_Profile_Malawi.pdf).

### 4. Geo-referenced apparent food consumption in Malawi (Se intake)

Fourth Integrated Household Survey 2016-2017. https://doi.org/10.48529/g2p9-9r19. It can be accessed through the World Bank microdata website. 

Information about each module and the information contained can be found [here](https://microdata.worldbank.org/index.php/catalog/2936/pdf-documentation)

**File of interest & variables**:

a. Food consumption

b. Geographic data (HouseholdGeovariablesIHS4.csv). This dataset has information on the displaced coordinates of each household, distance to some features (road, population centre, agricultural market, etc), and other enviromental variables (elevation, rainfall, etc).

Variables of interest:

-   case_id: Unique Household Identifier

-   HHID: household id (Survey Solutions Unique HH Identifier)

-   lat_modified: GPS Latitude Modified

-   lon_modified: GPS Longitude Modified

-   dist_road: HH Distance in (KMs) to Nearest Road

-   dist_agmrkt: HH Distance in (KMs) to Nearest Agricultural Market

-   ssa_aez09: Agro-ecological Zones

-   srtm_1k: Elevation (m)

c. Sales vs stored crops (rainy season) (AG_MOD_I)
d. Sales vs stored crops (dry (dimba) season) (AG_MOD_O)
d. Sales vs stored trees (12months) (AG_MOD_Q)

# Exploratory analysis

## 1) Micronutrient survey data (MW_WRA)

There are `r sum(!is.na(EligibleDHS$selenium))` entries for plasma Se in the dataset.

### Age
-  There are some observation (n = `r sum(Malawi_WRA$AGE_IN_YEARS<15 | Malawi_WRA$AGE_IN_YEARS>49)`) that are below the age range for WRA. 
In addition, mean (and median) were higher in the northern region compared with southern and center. Whereas, mean/median age were higher in rural areas. We applied survey weights when calculating them. 

### Gender & Pregnancy
- There is one entry labelled as "male" while the dataset should only contain women.  

### Height & Weight
-  There are outliers in height which are higher than 2m, some are coded as 999, we can assume those are missing values (NA) according to the coding standards reported in (ICF. 2018. Demographic and Health Surveys Standard Recode Manual for DHS7. The Demographic
and Health Surveys Program. Rockville, Maryland, U.S.A.: ICF). There is also one observation with a recorded height of 100.2.  
-  There are some outliers in weight as well of higher than expented, on the lower bound seems plausible given age and height.
-  We generated BMI variable which also has some outliers due to the high weight of some WRA. 

### Selenium

Se median (and mean) values were higher in urban settings than in rural, and the highest in the southern region. Then, the median dissagregated by region and urbanity showed that northern and southern urban population had the highest Plasma Se median, while the centre region were the lowest, particuarly for rural WRA. 

What it is interesting is that while the Northern-urban WRA had higher Se, than their southern counterpart, the Southern-rural WRA had higher plasma Se than their northern counterparts. In addition, wRA who live in urban setting of the centre region had similar plasma Se median concentration as women in the northern region in rural settings. 

## 2) Socio-Economic data (DHSDATA)

We extracted the socio-economic information from the DHS survey, however, we are only interested in the data that has Plasma Se values. 

According to the NSO (2017) report: Malawi Micronutrient Survey 2015-2016. There were significative differences between the number of indiviudals in each wealth quintile when disaggregated by rural/urban residency. 
#TODO: Would that impact our results? Probably yes. Check what that would mean for our analysis. 

In the same report, inflamation was reported around 12% but it was consistent across age groups, residency, and wealth Q. However, malaria prevalence was higher in rural areas and for the different wealth Q, w/ lowest WQ being 6-times higher than the highes WQ. Since, these two variables seemed to be also related to Plasma Se status. Can we identify if malaria is influencing Se status?
#TODO: Check correlation between malaria and Se status. 

When plotting wealth quintiles we can see that were more HH on the highest wealth Q. 

When plotting wealth and education, we can see that lowest wealth Q has no women with high education. 

Similarly, we can see that `r sum(DHSDATA$education_level >1 & DHSDATA$Literacy == 0)` women reported no literacy (0), but secondaty education (2).

All education and wealth level have representation in all three regions. Again, when looking at the data we could see that there is a slight "over-reporting" of the wealthiest Quintiles. 

## 3) Combining DHS datasets: Plasma Se & covariates

According to Phiri et al (2019), the influencing factors for Plasma Se (for WRA) in Malawi were soil type and proximity to Lake Malawi. 

In addition, other authors have reported that socio-economic characteristics may influence Se status. 

Here we are exploring the variabilty of Plasma Se according to those variables. First within the same dataset.


### Wealth
Plasma Se values were similar across wealth Q, with higher variability in the two lowest Q. 

### Education level
Plasma Se values were slightly higher in the highest education level, with lower variablity, while the opposite was true for the primary education level. 

### Place of residency

Plasma Se values were similar when aggregated by region, whereas we can start seeing some differences when we are plotting the results by district. Also notice, that the number of observations per district is 1) much smaller and 2) much diverse (from `r min(table(EligibleDHS$sdist))` to `r max(table(EligibleDHS$sdist))`). 

#REVIEW: Check weighting and how to apply them to the survey, including to plotting the data.
Because we are exploring how much Plasma Se variablity is explained by Maize Se concentration, we do not need to apply (or worry about) the weights. Only, we would need to apply them if we want to express some findings at population level, e.g., perc. of population at risk. We are not likely to do that, as 1) it is not the objective of the study/ model, and 2) we are working at certain scales where data will not be representative (e.g., district). 

#TODO: Check the data
What it would be important to check, it is wether the data is balance (e.g., highly skewed to one side and hence driving the model outcomes). 
We checked wealth by region and it seemed that there is a slight unbalance for the lowest Q in the middle region and towards the highes Q in the Northern region. 
See `r table(dhs_se$wealth_quintile, dhs_se$region)`. 

#TODO: Generate a dataset with districs and soil type, and proximity to the Lake Malawi (from the "centre of the district" to the lake) - Ask Liberty/ Louise whether that have been created previosly. 

### Smoking
Only 3 respondent reported smoking cigarettes, if we want to include this varable, we may need to combine with other smoking variables (including the other variables), although I believe that women who smoke in this context it may be very low.
#TODO: Check smoking incidence in WRA in Malawi.


After merging the datasets, some Wealth quintile were missing, hence following recomendations form F.S we used the household wealth quintile  for those available to impute it. This was available for 17 of the 39 observation with missing values.

For Plasma Se, we only have values for `r length(unique(EligibleDHS$sdist))`. This will condition the model choice.

## 4) Maize Se concentration in Malawi

We extracted the variables of interest from the dataset, then we are doing some data operations, for instance, removing NAs, and transforming Se in dry weight (mcg/kg DW) to Se in fresh weght (mcg/100g FW EP). 

#REVIEW: Moisture assumptions
Because, moisture content was not estimated, we are assuming same moisture content as the one measuere in the study of Hwang et al., (2016) for white maize. This is one of the assumptions that should be listed and tested, as for that study we have some data with their respective GPS, hence some extra analysis could be performed


There is a missmatch between the EAs and the maize Se conc. sampling. Resulting in 2200 () EAs without a maize Se conc. value. There are two potentital reasons for this to happen:

1) The boundaries are not equivalent with the coordinates. Making for the points to not be well nested or allocated to the correct EA. We have checked the method and it seemed that there is no issue with some points being either omitted. However, I believe that the values have been aggregated because there is no dupplicated ID_3.

Also there are 3 rows lost, which are also lost when subsetting using either st_within or st_intersect. This maybe due to 3 points being outside the boudaries used. 

#TODO: Check if the same is happening with district level boundaries (as they are more official)

2) No actual samples were collected for certain EAs.

It could be also a combination of both. 

## 5) Malawi GPS data & country boundaries 

We have found several shape files with the boundaries for Malawi. The issues is that not many of the files have the boundaries at EA level. 

This is due to the confidenciality as those are the cluster uses for most of the survey and are bases on the census data. 

One of good source of countries boundaries are GADM, we were using those boundaries the problem is that they include lake Malawi as part of the boundaries of the EA/district / state. Hence when using the boundaries to locate the HHs and/or maize it seems that part of the data is falling inside the lake. If we try to remove the lake area it leads to the missing of some observations. 

We are going to use other EA boundaries found [here]() from the World Bank and used previously by the NE Red Cross. 

If those are also not valid, then we will try to use the lak boundaries to "close" the distric boundaries near the lake in the GADM boundaries, or we could do the buffered boundaries based on the EA centroids. 

We have checked the new boundaries and they seemed correct, only that the areas when compared with the previous map are different. We are going to check that the distric reporoted in the DHS survey are the same as those allocated by binding the EA bounderies file. 

For those that the district are missing (NA) in the DHS, we would check that those points fall within what would be consided the district that it's reported in the EA boundaries file. Same for those with discrepancies. 

Then we will resolve accordingly. 

We have checked the discrepancies between the echo2 boundaries and the DHS with the NSO boundaries, and DHS and NSO are showing the same district. In addition, when we plotted the mismatched district we could visually check that NSO & DHS were assigning the correct district. 

Therefore, for district level we will use NSO boundaries. In addition, for the small scale units we are going to generate our own boundaries based on the centroids of the EAs. 

To do so, we will:

a) generate the centroids of each EA reprted in ECHO2 file.
b) draw a 2km-radious boundary for each centrod.In the future, we may want to differenciate between Rural and Urban EAs. 

After discussion with Claire (14/04/2023)

The three set of boundaries we are using are:
1) HH location based: We will draw buffers around the HHs of the WRA which donated blood for plasma Se. We will start with 5km buffer as it is the common displacement (geographic masking) used in rurar areas in DHS surveys. Then, we will create bigger buffer up to Admin boundaries and/or 100km radious (used for analisys of proximity to the market). 
2) Admin. unit based: We will start with Traditional Authorities, since we could not get good EAs boundaries (See above) and we will aggregate up to District/Region. 
3) Agro-eco based: Lastly, we will used the agro-ecological areas (also used in IHS4) to aggregate the data. #REVIEW: We were thinking to use the soil type as well, but maybe we will have some kind of cofounding if we are using that as one of the covariates of the model. 

Because of these tests should be run for all the datasets with boundaries. We have created a script where we are performing all these steps before the modelling, as this can be considered cleaning and processing previous the modelling. 

Then we will save the outputs in the inter-output folder, and use them in the model. 

After, we need to ask for the model that will provide an estimate (predicted-mean) of each area. The current model is only giving values for those areas with at least one observation. 

#### Household location-based aggregation

Test 1: Drawing a 10km buffer around the HH: we generate 10km buffer around each DHS HH location using the `st_butter()` function. The problem is that there are areas thar are outside the Malawi land. And, in addition, some of the buffers may be also within national parks where no maize samples were collected. Hence, we decided to use a different approach.

Test 2: [Non-overalpping join](https://r.geocompx.org/spatial-operations.html#non-overlapping-joins), which are based on proximity. We are merging DHS dataset with the GeoNutrition dataset using two functions: `st_join()` and `st_is_within_distance()`. It doesn't work because it use all the data in maize Se dataset.

If we are going to do a prediction we need to build the boudaries. Hence, ideally we should be able to calculate an area size, instead of a buffer. 


# Modelling

# To be tested:

1) Different buffer size (from 5km to 60km)
2) Cluster as random effect
3) Distance to inland water bodies 

### Model considerations

See model framework

p(s_i) = \apha(cluster) + \beta_1X_1 + \psi(s_i)


### Test 1: Irregular lattice model (areal data)

At EA level, it seemed that the random effect model was performing better than the spatial model, and convolution model.

At district level, it seemed that the convolution model was performing the best, followed quite closely by the random effect. 

For both aggregation levels, the likelihood models were showing opposite results as the other parameters (DIC and CPO). 

### Test 2: Geostatistics & point data