---
title: "Reproducible data documentation for the study on geospatial relationship between plasma Se concetration in WRA & maize grain Se concentration in Malawi"
format: html
editor: source
---

# Intro

The objectives of these exploratory analysis are:

1)  to calculate the mean/median wealth and education level for each EA in Malawi, and to see if there are differences

2)  to start evaluating how to calculate the mean/median maize Se concentration at different level of spatial aggregation (i.e., from 5km radius up to regional averages).

## Dataset & Variables

### 1. Geo-referenced crop (maize) composition (Se in maize) in Malawi

#### 1.1. Main dataset: GeoNutrition

This dataset was obtained from this [open repository](https://doi.org/10.6084/m9.figshare.15911973), and it is described by Kumssa et al, (2022). We decided to use this dataset instead of the one reported below (see excluded data sources) because it provided the raw dataset, as well as more metadata.

This repository contains a dataset with the raw values (i.e., as extracted from the analytical device), and a processed one, which has turned values which were not analysed (NM), below the limit of detection (<\LOD), or negative values into NAs.  This is problematic for our analysis as Se in Malawi was highly affected due to the very low values of Se in maize in that country. Therefore, some considerations were taken and are explained in the data exploration section (Section 2.x) as well as in the modelling section (Section 3.x). See also notes in Kumssa et al, (2022). 

#### 1.2. Complementary dataset: Chilimba 

b. Malawi maize grain and soil Se concentration dataset (2009-2010). It is publicly available [here](), but we obtained a more extensive dataset from the co-authors of the manuscript (L.A.) including the values of pH (in water) of the soil where samples were collected. 

File name: data/maize/AllanChilimbaFieldData_forLucia_20230615.xlsx

**Variables** 

#### 1.3. Excluded sources of data

a. Malawi maize grain and soil Se concentration dataset (2018). It is publicly available [here](https://github.com/rmlark/GeoNutrition/tree/main/Soil_Crop_comparisons/Malawi)

File name: GeoNutrition/Soil_Crop_comparisons/Malawi/Malawi_grain_soil.xlsx 
(data/maize/Malawi_Grain.csv)

Variables: 

-   Latitude/ Longitude*
-   Crop
-   Se_triplequad*
-   Zn
-   pH_Wa (pH in water)*
-   N_pct
-   Org_pct
-   BIO1*
-   BIO12
-   TIM


b. Malawi crops, including maize, mineral concentration dataset (2012-2013) and soil pH. It is publicly available [here](https://www.sciencedirect.com/science/article/pii/S0048969714014764). (Joy et al., 2014)(@ref) - **EXCLUDED** For more information check the section 2 (Cleaning and Exploratory analysis).

File source: Supplemantary data on https://www.sciencedirect.com/science/article/pii/S0048969714014764.

File name: 1-s2.0-S0048969714014764-mmc1.xlsx
File re-name: data/maize/2012_Joy-mwi-samples.

Tabs:1-10: Used in this analysis:
- STable6: crop sample info (maize Se) and coordenates
- STable5: Soil samples (soil pH)
- STable10: Information on each crop and its corresponding soil sample (Sample_number, Soil_sample).

**Cleaning script:** 00_cleaning_2012-Joy.R


### 2. Geo-referenced biomarkers data (Plasma Se in WRA) in Malawi 

Malawi DHS - MNS 2015-2016. Access need to be requested to DHS data [here](https://dhsprogram.com/methodology/survey/survey-display-483.cfm).

**File of interest & variables**:

a. Micronutrient survey data (MW_WRA). This dataset provided information on biomarker data and other biological data for women of reproductive age in Malawi. 

#TODO: Find the variable for CRP levels

-   mregion (region) [1-3 = N->S]
-   mtype (urban/rural) [U-R = 1-2] 
-   m04  (gender)
-   mcluster (cluster number - PSU?)
-   mnumber (husehold number)
-   mweight (Micro nutrient survey household weight (6 decimals))
-   m01 (line number - individual ID within HH)
-   m07 (age)
-   m435 (weight)
-   m436 (height)
-   sel (Plasma Se (ng/ml))
-   m415 (Took any kind of vitamin or mineral tablet/syrup/powder)
-   m431 (Malaria test result)
-   agp_crp_c1 (ANY_INFLAMMATION)

b. Questionnaire data (MWIR7). This dataset provided inforamtion on socioeconomic factors. We downloaded both the .dat and .dta file because the file with .dat extansion was not opening in R. It was not corrupted as we could open the .MAP with Notepad+, and we could see all recode doucmentation. 

These variables provide information at indiviual level.

Variables of interest:

-   v101/V024 (De facto region of residence)
-   sdist - (district). 
-   v022 (survey strata). Note that v022 & v023 are strata Urban/rural district. This shouldn't be used for MNS because the representativeness (and strata in MNS are region+rural/urban.
-   v005 (Woman's sample weights, divide it by 1000000 before applying the weighting factor). Not to be used for MNS, as MNS is a subset and has its own survey weights. 

-   v106 (Highest educational level)

-   v155 (Literacy)

-   v190 (Wealth index)
-   v190a (Wealth index for urban/rural) 

-   v002 (Household number)

-   v001 (Cluster number)

-   v463a (is_smoker, Only cover cigarettes (other smoking variables))

-   m420 (had_malaria)

-   v150 (Relationship to household head)

b.  MWGE7AFL (geographic data): Variable: DHSCLUST (to be used w/ V001). 

GPS displacement within district. Also, according to the documentation the cluster "centre" recorded is the "center of the populated place in the cluster" (GPS_Displacement_README, DHS, 2014).

#TODO: Check README and recommended readings to understand displacement and what it is possible and not possible for analysis. 

### 3. Boundaries of Malawi

Malawi administrative boundaries, from the higher to the smallest area: Region> District> Traditional Authorities (TA)> Enumeration Areas (EA). 

- 1. GADM maps and data, (gadm40_MWI_shp), https://gadm.org/download_country.html, The file for the EAs has some issues that lead some points in the lake. Hence, we found a different file with the Malawi boudaries, 

- 2. Malawi NSO from HDX (Humanitarian datasets), (mwi_adm_nso_hotosm_20230329), https://data.humdata.org/dataset/cod-ab-mwi

- 3. Population over Enumeration Areas NSO, (eas_bnd) https://www.masdap.mw/catalogue/#/dataset/126, This layer shows the distribution of the population over the country of Malawi on the basis of enumeration area boundary. Data producer is the National Statistical Office.

- 4. Echo2 priritization, These files covered up to EAs. (depricated - Updated version: Population over Enumeration Areas NSO)

- 5. GeoBoundaries: It also has 3 level of boudaries: 1-region, 2-district, 3-TA. These files has no EA boundaries (depricated).

Other boundaries in Malawi, including agro-ecological zones, agricultural land, body water, national parks, etc. 

We are not incluiding the AEZs boundaries because they are only 4 AEZs in Malawi, hence areas are too big to get any meanful spatial variation, and/or level of aggregation. Note: The AEZ can be found in the Scoping review (R project, data folder), and further inforamtion can be found in [here](https://climateknowledgeportal.worldbank.org/sites/default/files/2019-06/CSA%20_Profile_Malawi.pdf).

Excluded boundaries: Agro-Ecological Zones, Traditional Authorities (more information on data exploration). 

### 4. Geo-referenced apparent food consumption in Malawi (Se intake)

Fourth Integrated Household Survey 2016-2017. https://doi.org/10.48529/g2p9-9r19. It can be accessed through the World Bank microdata website. 

Information about each module and the information contained can be found [here](https://microdata.worldbank.org/index.php/catalog/2936/pdf-documentation)

**File of interest & variables**:

a. Food consumption

b. Geographic data (HouseholdGeovariablesIHS4.csv). This dataset has information on the displaced coordinates of each household, distance to some features (road, population centre, agricultural market, etc), and other enviromental variables (elevation, rainfall, etc).

Variables of interest:

-   case_id: Unique Household Identifier

-   HHID: household id (Survey Solutions Unique HH Identifier)

-   lat_modified: GPS Latitude Modified

-   lon_modified: GPS Longitude Modified

-   dist_road: HH Distance in (KMs) to Nearest Road

-   dist_agmrkt: HH Distance in (KMs) to Nearest Agricultural Market

-   ssa_aez09: Agro-ecological Zones

-   srtm_1k: Elevation (m)

c. Sales vs stored crops (rainy season) (AG_MOD_I)
d. Sales vs stored crops (dry (dimba) season) (AG_MOD_O)
d. Sales vs stored trees (12months) (AG_MOD_Q)


### 5. Enviromental covariates (Mean Annual Temperature)

a. mwi_CHELSA_bio10_1.tif: This raster dataset contains information on the Mean Annual Temperature (MAT) for Malawi from 1979-2013. 

The dataset is a cropped (clipped) area from the global (CHELSA_bio10_1.tf) which is a worldwide high resolution raster layer. The geographic coordinate system are referenced to the WGS 84 horizontal datum, with the horizontal coordinates expressed in decimal degrees. The dataset is in GEOtiff format and was extracted from the CHELSA dataset [here](https://datadryad.org/stash/dataset/doi:10.5061/dryad.kd1d4). This variable was used as enviromental covariates for the geospatial Se maize model (BIO1). 

The clipping was done on QGIS version (3.28.3) Firenze using the ea_bnd layer as reference extend for clipping. 

Secuence: Raster>Extraction>Clip Raster by Extend...>Clipping extent>Calculate from a layer> ea_bnd. 



# Cleaning & Exploratory Analysis

## 1) Se biomarker dataset (DHS)

### 1.1) Micronutrient survey data (MW_WRA)

There are `r sum(!is.na(EligibleDHS$selenium))` entries for plasma Se in the dataset.

#### Age
-  There are some observation (n = `r sum(Malawi_WRA$AGE_IN_YEARS<15 | Malawi_WRA$AGE_IN_YEARS>49)`) that are below the age range for WRA. 
In addition, mean (and median) were higher in the northern region compared with southern and center. Whereas, mean/median age were higher in rural areas. We applied survey weights when calculating them. 

#### Gender & Pregnancy
- There is one entry labelled as "male" while the dataset should only contain women.  

#### Height & Weight
-  There are outliers in height which are higher than 2m, some are coded as 999, we can assume those are missing values (NA) according to the coding standards reported in (ICF. 2018. Demographic and Health Surveys Standard Recode Manual for DHS7. The Demographic
and Health Surveys Program. Rockville, Maryland, U.S.A.: ICF). There is also one observation with a recorded height of 100.2.  
-  There are some outliers in weight as well of higher than expented, on the lower bound seems plausible given age and height.
-  We generated BMI variable which also has some outliers due to the high weight of some WRA. 

#### Selenium

Se median (and mean) values were higher in urban settings than in rural, and the highest in the southern region. Then, the median dissagregated by region and urbanity showed that northern and southern urban population had the highest Plasma Se median, while the centre region were the lowest, particuarly for rural WRA. 

What it is interesting is that while the Northern-urban WRA had higher Se, than their southern counterpart, the Southern-rural WRA had higher plasma Se than their northern counterparts. In addition, wRA who live in urban setting of the centre region had similar plasma Se median concentration as women in the northern region in rural settings. 

### 1.2) Socio-Economic data (DHSDATA)

We extracted the socio-economic information from the DHS survey, however, we are only interested in the data that has Plasma Se values. 

According to the NSO (2017) report: Malawi Micronutrient Survey 2015-2016. There were significative differences between the number of indiviudals in each wealth quintile when disaggregated by rural/urban residency. 
#TODO: Would that impact our results? Probably yes. Check what that would mean for our analysis. 

In the same report, inflamation was reported around 12% but it was consistent across age groups, residency, and wealth Q. However, malaria prevalence was higher in rural areas and for the different wealth Q, w/ lowest WQ being 6-times higher than the highes WQ. Since, these two variables seemed to be also related to Plasma Se status. Can we identify if malaria is influencing Se status?
#TODO: Check correlation between malaria and Se status. 

When plotting wealth quintiles we can see that were more HH on the highest wealth Q. 

When plotting wealth and education, we can see that lowest wealth Q has no women with high education. 

Similarly, we can see that `r sum(DHSDATA$education_level >1 & DHSDATA$Literacy == 0)` women reported no literacy (0), but secondaty education (2).

All education and wealth level have representation in all three regions. Again, when looking at the data we could see that there is a slight "over-reporting" of the wealthiest Quintiles. 

### 1.3) Combining DHS datasets: Plasma Se & covariates

According to Phiri et al (2019), the influencing factors for Plasma Se (for WRA) in Malawi were soil type and proximity to Lake Malawi. 

In addition, other authors have reported that socio-economic characteristics may influence Se status. 

Here we are exploring the variabilty of Plasma Se according to those variables. First within the same dataset.

#### Wealth
Plasma Se values were similar across wealth Q, with higher variability in the two lowest Q. 

#### Education level
Plasma Se values were slightly higher in the highest education level, with lower variablity, while the opposite was true for the primary education level. 

#### Place of residency

Plasma Se values were similar when aggregated by region, whereas we can start seeing some differences when we are plotting the results by district. Also notice, that the number of observations per district is 1) much smaller and 2) much diverse (from `r min(table(EligibleDHS$sdist))` to `r max(table(EligibleDHS$sdist))`). 

#REVIEW: Check weighting and how to apply them to the survey, including to plotting the data.
Because we are exploring how much Plasma Se variablity is explained by Maize Se concentration, we do not need to apply (or worry about) the weights. Only, we would need to apply them if we want to express some findings at population level, e.g., perc. of population at risk. We are not likely to do that, as 1) it is not the objective of the study/ model, and 2) we are working at certain scales where data will not be representative (e.g., district). 

#TODO: Check the data
What it would be important to check, it is wether the data is balance (e.g., highly skewed to one side and hence driving the model outcomes). 
We checked wealth by region and it seemed that there is a slight unbalance for the lowest Q in the middle region and towards the highes Q in the Northern region. 
See `r table(dhs_se$wealth_quintile, dhs_se$region)`. 

#TODO: Generate a dataset with districs and soil type, and proximity to the Lake Malawi (from the "centre of the district" to the lake) - Ask Liberty/ Louise whether that have been created previosly. 

#### Smoking
Only 3 respondent reported smoking cigarettes, if we want to include this varable, we may need to combine with other smoking variables (including the other variables), although I believe that women who smoke in this context it may be very low.
#TODO: Check smoking incidence in WRA in Malawi.


After merging the datasets, some Wealth quintile were missing, hence following recomendations form F.S we used the household wealth quintile  for those available to impute it. This was available for 17 of the 39 observation with missing values.

For Plasma Se, we only have values for `r length(unique(EligibleDHS$sdist))`. This will condition the model choice.

### 1.4) GPS location

It is at the cluster level, hence we need to check the variation within cluster as this will affect our model selection and results. 

## 2) Maize Se concentration in Malawi

### 2.1) GeoNutrition (Kumssa et al., 2022)

We extracted multiple variables of interest (including the LOD), which served to: 
    a) check the NAs values in the dataset (and previously reported in the now excluded dataset in Gashu et al., 2021), and
    b) to add those values as possible solution for accounting for the high number of missing Se conc. values.

Six Se values was not measure ID == c("MWI0574", "MWI1007","MWI1138","MWI1168","MWI1171","MWI1686") (see MWI_CropSoilData_Raw.csv), which needed to be transformed into `NA` in the variable `Se_std`. 

Additionally, the MAT should be added to this dataset as it is not inclued, as this study only reproted analytical data carried as part of the GeoNutrition. These values were completed when extracting the MAT for the Chilimba et al. (2011) sample locations. 
# REVIEW: For risk of bias (i.e., over-estimation and over-representation of high values).

#### Spatial pre-liminary analysis

a. The missing (i.e., <\LDO values) are spatially clustered, which probably will influence (unbalancing) our results (Kumssa et al, 2022). We hyposthesised that this is due to high concentration of very low Se conc. values in those affected regions. 

There is a missmatch between the EAs and the maize Se conc. sampling. Resulting in 2200 () EAs without a maize Se conc. value. There are two potentital reasons for this to happen:

1) The boundaries are not equivalent with the coordinates. Making for the points to not be well nested or allocated to the correct EA. We have checked the method and it seemed that there is no issue with some points being either omitted. However, I believe that the values have been aggregated because there is no dupplicated ID_3.

Also there are 3 rows lost, which are also lost when subsetting using either st_within or st_intersect. This maybe due to 3 points being outside the boudaries used. 

#TODO: Check if the same is happening with district level boundaries (as they are more official)

2) No actual samples were collected for certain EAs.

It could be also a combination of both. 

Low number of maize samples were found in the southern region of Malawi (Shire Valley), leading to a more sparce and higher uncertainty in that region. It could be because the harvest season is slightly earlier in that area and hence the fields were already plotted and other crops planted. (@ref). 

In order to minimise the impact on our model, and after checking that maize consumption is the same as other regions in Malawi (even slightly higher), we decided to include maize samples from other two studes (see data section & next section).

#### Fresh weight
#REVIEW: Moisture assumptions
Transforming Se in dry matter (mcg/kg DM) to Se in fresh weght (mcg/100g FW EP).

Because, moisture content was not estimated, we are assuming same moisture content as the one measuere in the study of Hwang et al., (2016) for white maize. This is one of the assumptions that should be listed and tested, as for that study we have some data with their respective GPS, hence some extra analysis could be performed


### 2.2) Mineral concentration in maize (Chilimba et al., 2011)

This dataset provided Se concentration in Maize grain and pH in soil (measured in water) for the same locations, however it did not contain informaiton on the mean annual temperature (MAT) (`BIO1`) for each location, which are used for the final model. 

We extracted the variable of interes, removed NA and check the coordinate projections to make sure both datasets (GeoNutrition & this dataset) were compatible (both datasets provided longitud and latitud data in decimal degrees, WGS84 datum, coordinate reference system EPSG:4326). 

When we checked the distribution of the sample we can see that the log-distribution shape is a bit odd. This may be related to the majority of the samples were collected from high Se conc. areas, which, paired with probably the omission of <\LOD, to a higher number of high concentration values. 
# REVIEW: Would it be adding more noise than helping the predictions?

### 2.3) Excluded datasets

#### 2.3.1) GeoNutrition (Gashu et al., 2021)

We extracted the variables of interest from the dataset: Se conc. (only in maize), pH, MAT, and the coordenates. Then we are doing some data operations, for instance, removing NAs (values >999) in Se conc. and checking missing values for the covariates. 

Two pH values were missing, hence we may exclude those values for the modelling, also there were three locations with missing MAT. This could be completed when extracting the MAT for the Chilimba et al. (2011) sample locations. 


#### 2.3.2) Mineral concentration in crops (Joy et al., 2014)

This study collected data for various crops, hence we needed to clean the dataset to obtain only the information for Maize Grain. We also excluded maize flour to keep it consistent with our dataset. In addition, soil pH values were obtained to be used as model covariates. 

However, GPS location were only provided for crops and not for soils, hence we were trying to use some information (STable10) to combine the sample number with the soil samples. These led to the correct allocation of a pH value for 57 of the 155 samples. 

Check what it is better, to allocate pH value by proximity or the mean pH value for the soil type.

According to the documentation, soil samples were not taken when the samples were collected at the market. We are then assuming that samples without pH value were collected at the market and hence should be excluded from our analysis. Then, only one or two samples were collected in the Shire Valley, thus this sample dataset will not be contributing substantially to reduce the uncertainty, and it may add other sources of variability (i.e., temporal, analytical, etc). Hence, it was excluded from the final dataset.

### 2.4) Mean Annual Temperature

Mean Annual Temperature (MAT) was used as enviromental covariates for the geospatial Se maize model. The data was extracted from the CHELSA dataset which was downloaded from [here]
(https://datadryad.org/stash/dataset/doi:10.5061/dryad.kd1d4) on 2023/07/17 and cropped for Malawi for easy usage. The geographic coordinate system are referenced to the WGS 84 horizontal datum, with the horizontal coordinates expressed in decimal degrees.  

### 2.5) Crop Se dataset

When we combined both GeoNutrition and Chilimba datasets. As expected, the Se concentration is heavily skewerd and it would need log transformation, while pH has a normal distribution. 

For more inforamtion on that see the exploratory analysis and the variable selection for the model reported in Gashu et al., (2019) [@ref] and the analysis done by Lark et al. (2019), here are the [scripts](https://github.com/rmlark/GeoNutrition/blob/main/Soil_Crop_comparisons/Malawi/Malawi_model.R). 

**Data issues**

- Low data availability in Southern region, in GeoNutrition, mainly other crops were collected (~11%)
- High proportion of below limit of detection values (~25%) 
- Leading to:
    - Potentail Over-estimation (or under-) of maize Se concentration
    - Not at-random missing values --> Spatial pattern
    - Reduced no. of co-located (maize Se & plasma Se) samples


## 3) Malawi GPS data & country boundaries 

We have found several shape files with the boundaries for Malawi (1-5).

### Boundaries data issues

The **first issue** that we encountered was that not many of the files have the boundaries at EA level. This is due to the confidenciality as those are the cluster uses for most of the survey and are bases on the census data. 

The **second issue** was that some boundaries are not accurated/ well-defined. For instance, in the dataset 1 (GADM), which is a good source of countries boundaries. However, after we found a problem whith the boundaries as that they include lake Malawi as part of the boundaries of the EA/district / state. Hence when using the boundaries to locate the HHs and/or maize it seems that part of the data is falling inside the lake. If we try to remove the lake area it leads to the missing of some observations. 

We are going to use other EA boundaries found [here]() from the World Bank and used previously by the NE Red Cross. 

If those are also not valid, then we will try to use the lake boundaries to "close" the distric boundaries near the lake in the GADM boundaries, or we could do the buffered boundaries based on the EA centroids. 

The **third issue** that we found was inconsistency between datasets. Although boundaries 2 and 3 are apparently produced by the NSO the number of TA are different (n=`length(unique(ea_bnd$TA_CODE))`) and (n=`length(unique(ta_bnd$ADM3_PCODE))`). The dissagrement may be due to the inclusion of sub-divided TA (i.e., TSA) in the dataset 3, or due differences on the date of the datasets. There are are small differernce sin the codes used between the datasets which may yielded further inconsistencies between the two. Hence, we may not use this aggregation unit for further analysis. 

- More info (on practical steps & tested thing on the notebook `Bondaries_notes.md`). 

#### Household location-based aggregation

Test 1: Drawing a 10km buffer around the HH: we generate 10km buffer around each DHS HH location using the `st_butter()` function. The problem is that there are areas thar are outside the Malawi land. And, in addition, some of the buffers may be also within national parks where no maize samples were collected. Hence, we decided to use a different approach.

Test 2: [Non-overalpping join](https://r.geocompx.org/spatial-operations.html#non-overlapping-joins), which are based on proximity. We are merging DHS dataset with the GeoNutrition dataset using two functions: `st_join()` and `st_is_within_distance()`. It doesn't work because it use all the data in maize Se dataset.

If we are going to do a prediction we need to build the boudaries. Hence, ideally we should be able to calculate an area size, instead of a buffer. 