---
title: "Methods: Model selection"
format: html
editor: source
---


# Model considerations

See model framework

### . Household location

The coordenates for the HHs are only provided at cluster level (EAs). Hence, we need to check first the variability within cluster. 

When we checked with boxplots (See 01_Explora_Malawi_model.R, line 258), the varibility of Plasma Se by EAs, we have realised two key things:
1) In general, we could assume that there is "low" EAs variability in the Plasma Se.
2) There is high variability within regions. As we can see by the scale of the plots, in northern region the scale ranged from 50-150nmol/mL, in central region from 0-300nmol/mL (#TODO:check the upper values here), with the highest values for Salima district (as expected), and the southern region ranged from 50-250nmol/mL.


It is important that we think about the displacement of the household location and the potential impacts on the final results. For instance, when two households are in the same EA, the maize Se value is the same for both households. 

See sensitivity analysis. 

## Parameter inclusion
(2023/08/16)

(2023/08/15)
We run it without the smoking variable (`is_smoker`) first because it was providing some errors (bc the varible class). We could add it in the future, and/or combine with the other smoking variables. 


```{r, }

# model to be fitted 
malawi.form <- log(Plasma_Se) ~ log(maizeSe_mean) +
wealth_quintile + BMI + urbanity + 
  had_malaria + ANY_INFLAMMATION

```

### Test 1: Irregular lattice model (areal data)

At EA level, it seemed that the random effect model was performing better than the spatial model, and convolution model.

At district level, it seemd that the convolution model was performin the best, followed quite closely by the random effect. 

For both aggregation levels, the likelihood models were showing opposite resutls as the other parameter. 

### Test 2: Point pattern model 



### Maize Se estimates

Predicted-mean Se concentration in maize at different level of aggregation were calculated using a Linear Mixed Model using pH & MAT as covariates and the aggregation unit as the random effect. The covariates were selected following Gashu et al, (2019) method. The covariates that were selected (significant) for the maize Se map (kringing map) were mean atmospheric temperature (MAT) and pH. See: `Explora_Malawi_model.R`.

#### Maize modelling issues (check notes:`Maize-model_notes.md`)
 



### . Other crops 

There were some discsusions around including or not other crops into the model. The rationale for inclusion is: 

1) the model will be more generalisable/ flexible: Because other countries may not have a unique dominant staple crop, as it is maize in Malawi. 
2) the model will account for spatial variation due to other crops, hence probably yielding more accurate results. 

However, the addition of more crops will add more complexity to the model due to:
 
 1) different crops may have a different food system. I.e, the catchment area (or foodshed), may be different. For instance, importing that crop or getting it from further away. 
 2) other crops are not equally important accross the country, and all of them are less consumed than maize in all districts (see image)
 3) there are other uncertainties that may play a role, for instance, sesonality and the displacement of the household location, that may be more difficult to characterise with a more complex model.

 In addition, with this analysis were are using maize Se as a proxy for a) the spatial variation of Se in crops-livestock-human, b) the foodshed and/or food catchment area, and c) maize is the main crop consumed accross the country in similar proportions (see images), while other grains are consumed in particular region and various amounts [@ref own analysis using IHS4]. We are not aiming to find a model that will be used to predict the plasma se of populations, as there are other potential sources of plasma Se variability that are not taken into consideration in this modelling excersise, such as fish intake, total food intake, etc. 


# Model assumptions


# Model selection


# Model validation & checks


## Sensitivity

### Household displacement

In order to see how the displacement may potentially affect the model results. We have displaced all/ X% of the sample within range. Hence, the point locations were displaced by 2km, and the analysis were re-run. 